name: build_windows

on:
  push:
    branches:
      - deployment

jobs:
  build:
    if: contains(github.event.head_commit.message, '[push windows]')
    runs-on: windows-latest
    environment: windows
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Install Windows SDK
        run: choco install windows-sdk-10.1
      - name: Install Certificate to Store and Clean Up
        run: |
          $base64EncodedCert = "${{ secrets.CERTIFICATE_ENCODED }}"
          $certBytes = [System.Convert]::FromBase64String($base64EncodedCert)
          [System.IO.File]::WriteAllBytes("simbrain.p12", $certBytes)
          $pfxPassword = ConvertTo-SecureString -String "${{ secrets.CERTIFICATE_PASSWORD }}" -AsPlainText -Force
          Import-PfxCertificate -FilePath "simbrain.p12" -CertStoreLocation Cert:\LocalMachine\My -Password $pfxPassword
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew signWindowsApp
        env:
          CERTIFICATE_SHA1: ${{ vars.CERTIFICATE_SHA1 }}
      - name: Install AWS CLI
        run: |
          choco install awscli -y

      - name: Configure AWS CLI for Cloudflare R2
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_KEY }}
          aws configure set default.region auto

      - name: Upload to Cloudflare R2
        shell: pwsh
        run: |
          $path = '.\build\dist'
          $files = Get-ChildItem -Path $path -Filter 'Simbrain*.exe'
          if ($files.Count -eq 1) {
            aws s3 cp $files[0].FullName s3://${{ secrets.CLOUDFLARE_R2_BUCKET }}/ --endpoint-url=https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          } elseif ($files.Count -eq 0) {
            Write-Error "No files found matching the pattern 'Simbrain*.exe' in $path"
          } else {
            Write-Error "Multiple files found matching the pattern 'Simbrain*.exe' in $path. Only one file is expected."
          }
